name: Image-Classification project workflow

on:
  push:
  branches:
    - main
  path-ignore:
    - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install -r requirements.txt

      - name: Run unit test
        uses: echo "Running unit tests"
        run: |
          pytest -v Image-Classification

build-and-push:
  name: Build and push artifacts
  needs: integration
  runs-on: ubuntu-latest
  steps:
